# The language in this case has no bearing - we are going to be making use of conda for a
# python distribution for the scientific python stack.
language: python

sudo: false

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"

       # Adds a GH_TOKEN (conda-forge-admin's conda-forge.github.io token)
       - secure: "xP8GJ7E8YvRMvFjnlNjvhcZB1YnC9J1tln1zJlX9EznyDjQOHNI590Z8VtJqtVuqZpkfz7LK/2eVA3KZJlA+OHm5uKSCUY6XOXd0GUcqCXmz+tTsEhpe51b7pDriDY398tsZCbV3YCx7AZcGlf2n7WaXytb1eGIchaIvmdwhWTqizDlWGa2+l1uE+4qHBRmF2XpkGx4pdlOCPV25oVbyfTHaxgvPC0QtaBk7vqu+sKeRHWhV2HFAFiMKKaSv6qrAh8cmoWb5lmPwB4fZktE0gfL+Seypw7CjBbW26+K2Wr9O37Vm+3GIhADrfNLXX0KV5cvJZ1LXeicKdG8wJjCoaZI+6Un+7iCx+OncJnQcPn5xIkdhMoqH1tnB52vZFhC60NxTFu4xOHT1N1+Igckbqt2k5NnPBKX3rweh5Pcw2puS+M2yibZw/p65Qxo5qTjp7qyOM7VVFZ1Rze3xbh+5wTWb49OcGEwM3xr3xVGkiytJSNzkMCdAyA1p1ahi8qqWCnlY0ayf1AOHu9CkPIO1TfF5bOsAUyLXIX5XYvO+7TCBGgu8UX0U0IVTAzzQg/vxOKoRLKQJbVdhAEPXneY3p6ifv++NM815DeHeKb7Fcwibmpb5hQZd6zdUuOvFCmH1r94pDngrtHcAnkYsSdQfoVUZEhLzjYmBwPXMDfj4Sa8="

    matrix:
        - ACTION="feedstocks_repo"
        - ACTION="update_docs"

install:
    - mkdir -p ${HOME}/cache/pkgs
    - "[ ! -f ${HOME}/cache/miniconda.sh ] && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/cache/miniconda.sh || :"
    - bash ${HOME}/cache/miniconda.sh -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    # Re-use the packages in the cache, and download any new ones into that location.
    - rm -rf ${CONDA_INSTALL_LOCN}/pkgs && ln -s ${HOME}/cache/pkgs ${CONDA_INSTALL_LOCN}/pkgs

    - git config --global user.name "Travis-CI on github.com/conda-forge/conda-forge.github.io"
    - git config --global user.email pelson.pub+conda-forge@gmail.com
    - mkdir -p ~/.conda-smithy && echo $GH_TOKEN > ~/.conda-smithy/github.token

    # Now do the things we need to do to install it.
    - conda install conda-execute --yes --quiet -c conda-forge

script:
    - if [ $ACTION = "update_docs" ]; then
        echo "Updating docs";
        source ./.ci_scripts/update_docs;
      elif [ "$ACTION" = "feedstocks_repo" ]; then
        echo "Updating feedstock repo";
        source ./.ci_scripts/update_feedstocks_repo;
      fi

# We store the files that are downloaded from continuum.io, but not the environments that are created.
cache:
    directories:
      - $HOME/cache
before_cache:
  # Remove all untarred directories.
  - find $CONDA_INSTALL_LOCN/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
