# The language in this case has no bearing - we are going to be making use of conda for a
# python distribution for the scientific python stack.
language: python

sudo: false

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"

       # Adds a GH_TOKEN (conda-forge-admin's conda-forge.github.io token)
       - secure: "cVJb7OGxeCTjh63ige+OYpQkTJgnCYOGk1plnghnKCjLcxKT87BA3iVo4rXMV2QFFrgr5kTvZiRnRswsFnyBF3gFyozIAWV/w1JQkqxzCtPxnkkQaz/JpNnDT84HR3KJYlUKMNq0Ak/VHf0y/ZNpnQnyyU3OTwtro5iuFcCUeGybGmRTbKoH8vXqUOD0w0P25/F8FljQeooYF1XYMnhRoMtEjAs/hzsJfs6rq+jPjDs7uky7HT4iqSWX5qRi69pgg1EudxNqkZJ3bK0y6bKL/2rL8QQHcvQnngwkj5t52WyxvCt3INZIZkTrojtkqpb/CL0ghYAOptgFDbTIj2YVxpkpfsusoLAo8ws7i1b9dfRKNLjuNia94BRQO2Wm6t6XmZACvMGBP25EGIxKXYaQx5NeDuSeRFwtob9holl5pFM4aowWPHWHqBi3KxGzZzP7b4N7q6ueoPclYWZKihTizYMmsxj8r9wZKpb79GSra36R6JSaHuT+i8PJYJlaz1C6iTBdWegyZaOvjYjrxZXQOBgiU8VjT4gkKmVxpYHEmKpM+2GkLcsYQDhJU2Z5geyFxCAeZ6xNGdV0sfZsI3yT0EdUZdIyJohus6jE50pl1kAebTrcEOYOuwLw9G40LB4nZ+NbOks1kvs8tq+Nk/h+NU+sY/zxFZTO50KdW9zoBKM="

    matrix:
        - ACTION="feedstocks_repo"
        - ACTION="update_docs"

install:
    - mkdir -p ${HOME}/cache/pkgs
    - "[ ! -f ${HOME}/cache/miniconda.sh ] && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/cache/miniconda.sh || :"
    - bash ${HOME}/cache/miniconda.sh -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    # Re-use the packages in the cache, and download any new ones into that location.
    - rm -rf ${CONDA_INSTALL_LOCN}/pkgs && ln -s ${HOME}/cache/pkgs ${CONDA_INSTALL_LOCN}/pkgs

    - git config --global user.name "Travis-CI on github.com/conda-forge/conda-forge.github.io"
    - git config --global user.email pelson.pub+conda-forge@gmail.com
    - mkdir -p ~/.conda-smithy && echo $GH_TOKEN > ~/.conda-smithy/github.token

    # Now do the things we need to do to install it.
    - conda install conda-execute --yes --quiet -c conda-forge

script:
    - if [ $ACTION = "update_docs" ]; then
        echo "Updating docs";
        source ./.ci_scripts/update_docs;
      elif [ "$ACTION" = "feedstocks_repo" ]; then
        echo "Updating feedstock repo";
        source ./.ci_scripts/update_feedstocks_repo;
      fi

# We store the files that are downloaded from continuum.io, but not the environments that are created.
cache:
    directories:
      - $HOME/cache
before_cache:
  # Remove all untarred directories.
  - find $CONDA_INSTALL_LOCN/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
