name: conda-forge-docs
channels:
  - conda-forge
dependencies:
  - python=3
  - conda-smithy
  - sphinx
  - cloud_sptheme
  - sphinxcontrib-fulltoc
  - elm
  - make
  - nodejs
  - xonsh
  - recommonmark